# Generated by Django 3.0.2 on 2020-07-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocations',
            options={'verbose_name_plural': 'allocations'},
        ),
    ]
