# Generated by Django 3.0.2 on 2020-07-16 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.polices')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.zones')),
            ],
        ),
    ]
